name: gha-test

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      COV: ${{ steps.cov.outputs.COV }}
    steps:
      - id: cov
        run: |
          sleep 10
          echo "COV=90" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    outputs:
      COV: ${{ steps.cov.outputs.COV }}
    steps:
      - id: cov
        run: |
          sleep 10
          echo "COV=100 >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - run: |
          echo "job1 cov=${{ needs.job1.outputs.COV }}"
          echo "job2 cov=${{ needs.job2.outputs.COV }}"
