name: gha-test

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "job2

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - run: echo "job3"
